// <auto-generated />
using Category_Product_Management.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Category_Product_Management.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260817134334_AddMoreProductProperties")]
    partial class AddMoreProductProperties
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Category_Product_Management.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImagePath = "categories/electronics.jfif",
                            Name = "Electornics"
                        },
                        new
                        {
                            Id = 2,
                            ImagePath = "categories/food.jfif",
                            Name = "Food"
                        });
                });

            modelBuilder.Entity("Category_Product_Management.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 2,
                            Description = "A good sushi",
                            ImagePath = "products/food/sushi.jfif",
                            Name = "Sushi",
                            Price = 39.99f
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Description = "Amazing vegetables pizza",
                            ImagePath = "products/food/pizza.jfif",
                            Name = "Pizza",
                            Price = 5.65f
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "Smart good big TV",
                            ImagePath = "products/electronics/tv.jfif",
                            Name = "TV",
                            Price = 200.99f
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Description = "Fast small powerfull IPhone",
                            ImagePath = "products/electronics/phone.jfif",
                            Name = "Phone",
                            Price = 399f
                        });
                });

            modelBuilder.Entity("Category_Product_Management.Models.Product", b =>
                {
                    b.HasOne("Category_Product_Management.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Category_Product_Management.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
